### ISSUE TITLE
Feature request: Add focus

### ISSUE THREAD

**Issue by corysimmons** [andrewbranch/react-use-hover#42]
It'd be nice to have a way to indicate the attempt to hover something on mobile by letting focus work the same as hover.

Basically the user taps on something, it gets focus, it stays "hovered" until they tap something else.

This would need to be opt-in behavior rather than by default.

**Comment by andrewbranch** [comment]
Basically you want a boolean state container toggled by `focus` and `blur`? Seems like a good hook to have, but it doesn’t actually sound related to hovering 😄

**Comment by corysimmons** [comment]
Yeah maybe not related but it seems like it should go with this lib.

Rename lib to `react-use-hoverish`? :D

**Comment by andrewbranch** [comment]
Here’s a reusable hook factory that reduces this entire library, along with the thing you want, down to one line each:

```ts
import React, { useState } from 'react';

type Handler = Exclude<{
  [K in keyof React.DOMAttributes<any>]: React.DOMAttributes<any>[K] extends ((...args: never[]) => unknown) | undefined
    ? K
    : never
}[keyof React.DOMAttributes<any>], undefined>;

export interface BooleanSwitchOptions {
  onDelayMS?: number;
  offDelayMS?: number;
}

function createUseBooleanSwitch(on: Handler, off: Handler) {
  return ({ onDelayMS = 0, offDelayMS = 0 }: BooleanSwitchOptions = {}) => {
    const [state, setState] = useState(false);
    let onTimer: number | undefined;
    let offTimer: number | undefined;

    return [
      state,
      {
        [on]: () => {
          clearTimeout(offTimer);
          onTimer = setTimeout(
            () => setState(true),
            onDelayMS
          );
        },
        [off]: () => {
          clearTimeout(onTimer);
          offTimer = setTimeout(
            () => setState(false),
            offDelayMS
          );
        },
      },
    ] as const;
  }
}
```

Usage:

```tsx
const useHover = createUseBooleanSwitch('onMouseEnter', 'onMouseLeave');
const useFocus = createUseBooleanSwitch('onFocus', 'onBlur');

function Component() {
  const [isHovering, hoverProps] = useHover();
  const [isFocused, focusProps] = useFocus();
  return (
    <a {...hoverProps} {...focusProps}>Hover/focus me</a>
  );
}
```

[TypeScript playground](https://www.typescriptlang.org/play/?jsx=2&ssl=1&ssc=1&pln=51&pc=2#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxJwC+cAZlBCHAORSoYsDcAUDzAE8wVABIoAdgBMANkihwAvHACiADzTT8kpAB4cPOHADaAaTjBxcANZIBEOog4wAdABEA8gFkAgjBhRgACN8SkIdCQEAPgBdAC5HdBcPHz8A4NDw8SjTaLgkVUopQjgAChLnCpQoAHNCePEkADc5I2iASkVIgnErcQgAd3EOgB9u7ToLJEkDQzgAfjgTGcN6prkeaiMbOwdkRLcvX38gkKQwiJjsfCkkCYbJSN4efMhYc3FKKDp0KgAhCAgsgkJH6wBgaAAFu4wDBgBBxMV9IZ4a4kNIUAJPCQ5vV8CBAnJeMi6HRUejMdjcfjCRs+HRrhg4ZY0OwKEgAKrEf6A1DiEFgyEleHxMRSWRQbD2OgiiQyOQdJFwdgwfBQSwlPAotEYrGKOAABklJLJOpIev1NHi3KBfNB4KhMKZxSUOGoHQUXUVhjQ8MI8CMfrZ2GIMDIbNySiIpHIlBK32kxDaRNmsng8IAKqA5FSCfJRtdxpNJMnDKm4FLMyBs3BxHjc3B8zc7lMnrMlUgVWrjMtZoHKJge4YvW3jPC4qV3Z7ByONKgoJWkBAQkKSQuoEnp22M1n5EoQwulzASpuRyVJ3AQ2HY-58Eg2gOR4-y+ITRST4YN0+aA+n0YpeOz06XB3zgWcqgPZdtyrdcSyfCsdz1fcs0PY8vzbQCPQvDsryQOMUATO8fzQ8tjW1N9iM-J9qCI2ZqJ7XIUGKH0ERgZNqFpHhmL9AhiBECBml3UDWUoTkkGtXl+XtEoWHhTwl2IZQPjkFhsBk8Q5KjAAZVBmhYDcuPgKMADEIDQIg9RZVARK5AEbUkwU1JMszCBU1h4V+TQoD0p56XERl4TgABhJhIAaD5AMVAzjGAQg+IEixqmwCF+LkAAFRgwEICMeKQOK5DPZMoqMGKnKjSRsDoUyiHSiBMuy4yqsIAqZmVVV1R7cJcAqZxkoEmrMtoHBusq5z+sIahIjyqAAHoRvMqsdGmlBIhmDdqCAA)

Licensed under [WTFPL](http://www.wtfpl.net) 😛 

In slightly more seriousness, I did end up modifying this hook for a better mobile experience for my blog. Generally hover on mobile is an antipattern, but I had kind of a weird use case where nothing else would do, and found it worked better with `onTouchStart`. https://github.com/andrewbranch/blog/blob/master/src/hooks/useHover.ts

I’m probably not going to add this to react-use-hover, because, well, I made the mistake of naming it kind of specifically when it can be trivially reduced to a one-liner like that. Let me know if you publish `react-create-use-boolean-switch` and maybe I’ll be a user! 😄

**Comment by corysimmons** [comment]
Really nice Andrew! I feel bad npm publishing your work, but I bet it'd be handy in lots of situations.

Something like Lodash's modules would be nice for this.

```js
import { useHover, useFocus } from 'usefull`
```

How many interactions are there anyway?

- `useScroll` for when someone is scrolling inside a component
- `useResize` for when someone is resizing a component

Thoughts?

**Comment by andrewbranch** [comment]
If all you need is “is currently scrolling” or “is currently resizing,” this would probably be enough. But I can also imagine in those scenarios you might want to get more info out than just a boolean. For example, I wrote a [hook](https://github.com/andrewbranch/blog/blob/master/src/hooks/useScrollDepth.ts) that let me fire specific handlers as a user scrolls past N% of a page. As far as having a lodash-esque collection of simple hooks, check out [awesome-react-hooks](https://github.com/rehooks/awesome-react-hooks). They’re mostly packaged individually, I think, but looking at a curated list of existing packages is nice.

**Comment by corysimmons** [comment]
Cool thanks so much Andrew. =)
